Logcxx-521
apache/logging-log4cxx pull request #59
Opened 2021-03-29 23:33 UTC by rm5248

Link with ODBC library if found on OSX and Linux.

2021-03-30 08:37 UTC, ams-tschoening requested changes
Minor code style changes, but hings built for me as well.

2021-03-30 08:37 UTC, ams-tschoening commented on src/main/include/CMakeLists.txt
> +	set(HAS_ODBC 1)
tabs vs. spaces as well.

2021-03-30 08:37 UTC, ams-tschoening commented on src/CMakeLists.txt
> +	target_link_libraries( log4cxx PRIVATE ${odbc_LIBRARIES})
These lines mixed tabs and spaces.

2021-03-30 22:23 UTC, rm5248 commented
Dang... not sure how those spaces keep creeping in.  I'll look into making a pre-commit hook to check for those, it should help reduce those errors.  Should be fixed now though.

2021-03-31 09:29 UTC, ams-tschoening approved these changes

2021-03-31 09:32 UTC, ams-tschoening commented
> Dang... not sure how those spaces keep creeping in.[...]

`.editorconfig` is the root cause most likely, that contains spaces for shell scripts and `CMakeLists.txt`:

```ini
[*.sh]
charset						= utf-8
end_of_line					= lf
indent_size					= 2
indent_style				= space
insert_final_newline		= true
tab_width					= 2
trim_trailing_whitespace	= true

[CMakeLists.txt]
charset						= utf-8
end_of_line					= lf
indent_size					= 2
indent_style				= space
insert_final_newline		= true
tab_width					= 2
trim_trailing_whitespace	= true
```

Looking at the logs, you seem to have simply copied the block for shell scripts, maybe because some of those files didn't follow the other style guide then. In the easiest case it might get removed so that it's handled by `*`.

2021-04-01 00:24 UTC, merged